name: "💡 New Feature"
description: Suggest an idea for this project
title: "💡 "
labels: "Type: feature :bulb:"
body:
  - type: markdown
    attributes:
      value: |
        Please complete the below details about the feature requirements. 

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description:  "Describe the feature from the perspective of the user and the problem it solves. Use the format: As a <type of user>, I want <some goal> so that <some reason> if it helps."
      placeholder: As a <type of user>, I want <some goal> so that <some reason> (e.g., As an admin, I want to be able to schedule automated backups so that I can ensure data security).
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Outline the criteria that must be met for this feature or change to be considered complete.
      placeholder: "Describe the acceptance criteria (e.g., - The feature should be tested on all major browsers and devices. - The performance impact should be minimal)."

  - type: textarea
    id: tasks
    attributes:
      label: Tasks
      description: "Link to any issues that need completing before this issue here, e.g. - [] #32"
      placeholder: "- [] #32"

  - type: textarea
    id: more-info
    attributes:
      label: More Information
      description: "An area to capture any additional information about the feature"
      placeholder: Provide any additional information or links to relevant resources.
