name: "🧠 Initiative"
description: "Defines a broad, high-level goal."
title: "🧠 "
type:
  - "Initiative"
body:
  - type: markdown
    attributes:
      value: |
        Use this template to define a high-level goal that will be broken down into Features and Development Units.

  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      description: "Provide a clear, concise overview of the initiative and its purpose."
      placeholder: "Summarize the initiative's purpose, scope, and context."
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: "Tasks / Sub-Issues"
      description: "List the Features or Development Units that will be created as part of this initiative."
      placeholder: |
        - [ ] Create Feature: User authentication
        - [ ] Create Feature: New onboarding flow
        - [ ] Link related issues
    validations:
      required: false

  - type: textarea
    id: more_info
    attributes:
      label: "More Information"
      description: "Include any relevant links, documentation, or background information."
      placeholder: "Add context, links to designs, technical notes, or external documents."
    validations:
      required: false
