name: "💡 Feature"
description: "Describes a focused capability or functionality within an initiative."
title: "💡 "
type: "Feature"
labels:
  - "Type: feature :bulb:"
body:
  - type: markdown
    attributes:
      value: |
        Use this template to describe a mid-level feature that contributes to a broader initiative. This should define the purpose and scope of the feature. Sub-issues (e.g., Development Units) will be created separately by the development team. **Note: this template should only be used in the tep-documentation repository!**

  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      description: "Provide a high-level overview of this feature, including its purpose and how it supports the broader initiative."
      placeholder: "Describe the capability this feature provides and why it's important."
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: "Tasks / Sub-Issues"
      description: "Link any related Development Units or lower-level issues that support this feature."
      placeholder: |
        - [ ] #123 Add password reset UI
        - [ ] #124 Implement backend logic
        - [ ] Link to related issues
    validations:
      required: false

  - type: textarea
    id: more_info
    attributes:
      label: "More Information"
      description: "Add any relevant designs, documentation, or context that helps clarify the feature."
      placeholder: "Link to Figma files, specifications, or technical notes."
