name: "🐛 Bug Report"
description: "Create a report to help us improve"
title: "🐛 "
labels:
  - "Type: bug :bug:"
body:
  - type: markdown
    attributes:
      value: |
        Please complete the below forms about the bug.

  - type: textarea
    id: bug_description
    attributes:
      label: "Describe the Bug"
      description: "A clear and concise description of what the bug is."
      placeholder: "Enter bug description here"
    validations:
      required: true

  - type: textarea
    id: reproduce_steps
    attributes:
      label: "To Reproduce"
      description: |
        Steps to reproduce the behaviour:
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See the error
      placeholder: "List the steps to reproduce the bug if appropriate"

  - type: input
    id: expected_behavior
    attributes:
      label: "Expected Behaviour"
      description: "A clear and concise description of what you expected to happen."
      placeholder: "Enter expected behaviour here"

  - type: checkboxes
    id: tasks
    attributes:
      label: "Tasks"
      description: "Select the tasks for this issue"
      options:
        - label: "Investigate"
        - label: "Fix"

  - type: textarea
    id: more_information
    attributes:
      label: "More Information"
      description: "Add any other context about the problem here"
      placeholder: "Enter additional details or links"

  - type: input
    id: environment
    attributes:
      label: "Environment"
      description: |
        Provide the details of your environment:
        - Device: e.g., iPhone 12
        - Browser: e.g., Chrome, Safari
        - OS: e.g., iOS
      placeholder: "Enter environment details here"

  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots"
      description: "If applicable, add screenshots to help explain your problem"
      placeholder: "Provide a link or attach screenshots"
