name: "👷 DevOps"
description: "Submit tasks related to CI/CD pipelines, infrastructure, deployment processes, or other operational improvements."
title: "👷 "
type: "Dev Ops"

body:
  - type: markdown
    attributes:
      value: |
        Please fill out this form to describe the current challenge or opportunity related to our infrastructure, CI/CD pipelines, deployment processes, or other operational aspects, and provide your proposed solution.

  - type: textarea
    id: pain
    attributes:
      label: "Current Challenge or Opportunity"
      description: "Describe the current pain point, inefficiency, limitation, or enhancement opportunity."
      placeholder: "Explain the challenge or opportunity here"
    validations:
      required: true

  - type: textarea
    id: suggested_solution
    attributes:
      label: "Proposed Solution or Improvement"
      description: "Detail the solution, improvement, or change you propose to address the challenge or seize the opportunity."
      placeholder: "Describe your proposed approach"
    validations:
      required: false

  - type: checkboxes
    id: tasks
    attributes:
      label: "Tasks"
      description: "Select the tasks needed to implement the solution or improvement."
      options:
        - label: "Update pipeline configuration"
        - label: "Test the new setup"
        - label: "Document the changes"
        - label: "Notify stakeholders"

  - type: textarea
    id: more_information
    attributes:
      label: "Additional Context or References"
      description: "Add any relevant details, links, logs, or documentation to support this request."
      placeholder: "Provide supporting information here"

  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots, Logs, or Outputs"
      description: "If applicable, attach screenshots, error logs, or other outputs that help illustrate the issue or proposed changes."
      placeholder: "Attach logs or screenshots"
